name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]
    branches: [ issues/15 ] # TODO: マージされたら削除

jobs:
  cd:
    runs-on: ubuntu-22.04
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.0'
    - name: Create .tfbackend
      run: echo '${{ secrets.TF_BACKEND }}' > .tfbackend
    - name: Terraform Init
      run: terraform init -backend-config=.tfbackend
    - name: Create terraform.tfvars
      run: echo '${{ secrets.TF_VARS }}' > terraform.tfvars
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
