name: ci

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.0'
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create .tfbackend
      run: echo '${{ secrets.TF_BACKEND }}' > .tfbackend
    - name: Create .tfvars
      run: echo '${{ secrets.TF_VARS }}' > terraform.tfvars
    - name: Terraform Init
      run: terraform init -backend-config=.tfbackend
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Validate
      run: terraform validate
