name: ci

on: [ push ]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.0'
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Extract Azure Credentials
      run: |
        echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.clientId' | awk '{print "ARM_CLIENT_ID="$1}' >> $GITHUB_ENV
        echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.clientSecret' | awk '{print "ARM_CLIENT_SECRET="$1}' >> $GITHUB_ENV
        echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.tenantId' | awk '{print "ARM_TENANT_ID="$1}' >> $GITHUB_ENV
        echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.subscriptionId' | awk '{print "ARM_SUBSCRIPTION_ID="$1}' >> $GITHUB_ENV
    - name: Create .tfbackend
      run: echo '${{ secrets.TF_BACKEND }}' > .tfbackend
    - name: Terraform Init
      run: terraform init -backend-config=.tfbackend
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Validate
      run: terraform validate
